# Generated by packaging/homebrew/formula.sh. Do not edit by hand: every
# release overwrites this file.
class Perch < Formula
  desc "Run Claude Code as whichever Claude account you want, without logging in again"
  homepage "https://github.com/perch-cli/perch"
  version "0.2.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/perch-cli/perch/releases/download/v0.2.0/perch-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "dfd1c5033303975fd03d0c42875e916bf46b53a120c4244495e3d60733dd9b0b"
    end

    on_intel do
      url "https://github.com/perch-cli/perch/releases/download/v0.2.0/perch-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "dc47bcdaa7ae2455d5ee926af55ae0349c475f2c999cc76eec52885362ea3988"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/perch-cli/perch/releases/download/v0.2.0/perch-v0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c172cadf4356c3b5a649db3918372c678dbaca2cd3b05b86f3335047e9b072ab"
    end

    on_intel do
      url "https://github.com/perch-cli/perch/releases/download/v0.2.0/perch-v0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "33766b3adfdf4145cff2859b52d2747b2b4dd57044ef2772090d1c67fc4372e4"
    end
  end

  def install
    bin.install "perch"
  end

  test do
    assert_match "perch #{version}", shell_output("#{bin}/perch --version")
  end
end
